### ISSUE TITLE
django-tree can not be installed

### ISSUE THREAD

**Issue by jhonvidal** [BertrandBordage/django-tree#2]
django-tree can not be installed for versions of django 1.8, 1.9 and 1.11.5.

Currently testing with django 1.11.5, I get the following error:

`(vtree) [white@ban exampletree]$ pip install django-tree
Collecting django-tree
  Could not find a version that satisfies the requirement django-tree (from versions: )
No matching distribution found for django-tree`

can you update it please

**Comment by BertrandBordage** [comment]
It can be installed with django 1.8, 1.9 & 1.10, as listed in the requirements.
I don’t have time to work on it for now sorry.
If you’re willing to sponsor open source development on this project, you’re welcome!

**Comment by BertrandBordage** [comment]
I guess this can be considered as kind of resolved, now that django-tree supports Django 3.2.
I know, it needs some packaging efforts to be more up to date + CI/CD.
No time for that now, but this project will keep being updated over the years.
